### ISSUE TITLE
Add class to container <li> example?

### ISSUE THREAD

**Issue by Coufu** [yannickoo/menu_link_attributes#42]
I read the documentation, but I can't seem to get it to work. This is my YAML file. Then after I use the form to add some classes to that menu item, the classes don't get added to the \<li\>. The class for the \<a\> shows up though so I know that's working.
```yaml
attributes:
  container_class:
    label: 'Class(es) to add to container &lt;li&gt;'
    description: ''
  class:
    label: 'Class(es) to add to the link &lt;a&gt;'
    description: ''
  target:
    label: ''
    description: ''
    options:
      _blank: 'New window (_blank)'
      _self: 'Same window (_self)'
```
